### ISSUE TITLE
Update release with fixed logging

### ISSUE THREAD

**Issue by TokcDK** [BepInEx/IPALoaderX#3]
Would you update releases bin with latest changes where fixed logging? Because with v1.1 it is just trowing exception with logging error and it is not working with Bepinex v5. I have VS and compilled it for myself(attached for any cause) but still would be better if releases will be updated.
And forgot to say I moved main dll from BepinEx to BepinEx\plugins\ folder to be possible to load it with BepinEx 5 (atleast with default path for plugins dir in BepinEx cfg).

[IPALoaderX (commit Jul 22, 2019 For BepinEx 5).zip](https://github.com/BepInEx/IPALoaderX/files/3464665/IPALoaderX.commit.Jul.22.2019.For.BepinEx.5.zip)

And second question. Which variant of Bepinex can be used to attach this plagin to Honey select? I saw in readme text about Honeyselect but tried several variants of BepinEx for HS and the plugin was no attached with any of them but it working for example with com3d2.

**Comment by Keelhauled** [comment]
Try changing the entrypoint in the bepinex config.ini like this for HS
```
[Preloader]
entrypoint-assembly=UnityEngine.dll
entrypoint-type=MonoBehaviour
entrypoint-method=.cctor
```

**Comment by TokcDK** [comment]
Assembly and method was correct and autodetected by legacy version but type was incorrect and even if game was loaded just with BepinEx5 but with IPALoaderX it was crashing after some time. Checked again with changed type and it now working and loading IPA plugins. Thanks for the info.

**Comment by TokcDK** [comment]
Keelhauled, other question. Maybe you known if somewhere exist standalone dll of Wideslider patcher for HS as dll plugin for IPA\BepinEx to replace patching method without need to touch game files? Like it was made with MoreSlotID for HS (included in HSConflictResolverMoreSlotID) or like patched dll for 4k was replaced by your standalone Harmony4KPatch dll plugin.

**Comment by Keelhauled** [comment]
That might be the only plugin that doesn't have a harmony version still. I can't say for sure though. You could try making it yourself, it shouldn't be too difficult.

**Comment by TokcDK** [comment]
Ok. Understood.
